apiVersion: v1
kind: Service
metadata:
  namespace: ornl
  name: es-client-lb
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app: elasticsearch
    role: client
  ports:
    - name: http
      protocol: TCP
      port: 9200
      # targetPort: 5601
  