apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ornl
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.8.0
        ports:
        - containerPort: 5601
          name: kibana-service
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://es-client.ornl.svc.cluster.local:9200"
        # - name: ELASTICSEARCH_USER
        #   value: "elastic"
        # - name: ELASTICSEARCH_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: es-pw-elastic
        #       key: password
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
        # - name: es-certs
        #   mountPath: /usr/share/kibana/config/certs/es
        #   readOnly: true
        # - name: kibana-certs
        #   mountPath: /usr/share/kibana/config/certs/kibana
        #   readOnly: true
      volumes:
      - name: config
        configMap:
          name: kibana-config
      # - name: es-certs
      #   secret:
      #     secretName: es-client-cert
      # - name: kibana-certs
      #   secret:
      #     secretName: kibana-tls