apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: ornl
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - datawookies-visualize.c2labs.com
    secretName: kibana-tls
  rules:
  - host: datawookies-visualize.c2labs.com
    http:
      paths:
      - backend:
          serviceName: kibana-service
          servicePort: 5601
        path: /(.*)