apiVersion: v1
kind: Service
metadata:
  namespace: ornl
  name: kibana-service
spec:
  # type: ClusterIP
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: http
      protocol: TCP
      port: 5601
      # targetPort: 5601
  