trigger:
  - master

stages:
- stage: Build
  jobs: 
  - job: BuildDatawookies
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo "##vso[task.setvariable variable=commit-tag]$(echo $BUILD_SOURCEVERSION | cut -c 1-7)"
        displayName: 'Set Commit Tag'

      - task: Docker@2
        displayName: 'Build Image and Push to ACR'
        inputs:
          containerRegistry: 'C2 Container Registry'
          repository: 'datawookies'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(commit-tag)
                   
- stage: Deploy
  pool:
    vmImage: 'ubuntu-latest'
  jobs: 
    - job: DeployDatawookies
      steps:
        - script: echo "##vso[task.setvariable variable=commit-tag]$(echo $BUILD_SOURCEVERSION | cut -c 1-7)"
          displayName: 'Set Commit Tag'
            
        - task: Kubernetes@1
          displayName: 'Deploy Datawookies with New Image'
          inputs:
            kubernetesServiceEndpoint: 'AKS Datawookies'
            namespace: 'ornl'
            command: set
            arguments: 'image deployment/datawookies datawookies=c2labs.azurecr.io/datawookies:$(commit-tag) --record'