apiVersion: apps/v1
kind: Deployment
metadata:
  name: datawookies
  namespace: ornl
spec:
  selector:
    matchLabels:
      app: datawookies
  replicas: 1
  template:
    metadata:
      labels:
        app: datawookies
    spec:
      containers:
      - name: datawookies
        image: c2labs.azurecr.io/datawookies:0.0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: datawookies-service
  namespace: ornl
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: datawookies